version: '3.8'

services:
  tika-server:
    image: apache/tika:latest
    container_name: tika-server
    ports:
      - "9998:9998"

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
    volumes:
      - weaviate_data:/var/lib/weaviate

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tesis-backend
    ports:
      - "4000:4000"
    environment:
      - TIKA_URL=http://tika-server:9998
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - MONGO_URI=mongodb://root:example@mongodb:27017/tesis?authSource=admin
      - NODE_ENV=development
    depends_on:
      - tika-server
      - weaviate
      - mongodb
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tesis-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  weaviate_data: {}
  mongodb_data: {}
